Resources:
  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PatientData
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
